baseURL = "http://andressaga.es/"
languageCode = "es-es"
author = "Andrés Sáncher García"
title = "Otro blog mas"
theme = "hugo-goa"

publishDir = "docs"
googleAnalytics = "UA-52491226-1"


[params]
	author = "Andrés Sáncher García"
  intro = "DevOps"
	description = "Trabajando en Sacyl, migrando a una infraestructura como código :-P"
	authorimage = "avatar.png"
	dateformat = "Jan 2, 2006"
[params.meta]
	description = "devops infraestrutura como código"
	keywords = "devops,IAC,python,golang,docker,rancher"

[params.social]
	github = "asg1612"
  twitter = "asg1612"
  linkedin = "asg1612"
  email = "asg1612@gmail.com"


[[menu.main]]
	name = "blog"
	weight = 100
	url = "blog"
[[menu.main]]
  name = "about"
  weight = 200
  url = "/about/"
